### ISSUE TITLE
Completion not working

### ISSUE THREAD

**Issue by Copper0292** [seblj/roslyn.nvim#95] opened 2024-11-28 20:38 UTC
Hi, thank for your efforts on making this LSP work!

I'm trying this plugin and everything seems to work, except for the code completion with nvim-cmp. Is there something I'm missing?

This is my `nvim-cmp` config:

```lua
{
    'hrsh7th/nvim-cmp',
    event = 'InsertEnter',
    dependencies = {
      'hrsh7th/cmp-buffer',
      'hrsh7th/cmp-nvim-lsp',
      'saadparwaiz1/cmp_luasnip',
      'hrsh7th/cmp-path',
      'ray-x/cmp-treesitter',
      'onsails/lspkind-nvim',
      { 'zbirenbaum/copilot-cmp', config = true },
    },
    opts = function()
      local cmp = require('cmp')
      local lspkind = require('lspkind')
      local luasnip = require('luasnip')
      local source_names = {
        copilot = '[Copilot]',
        buffer = '[Buffer]',
        luasnip = '[Snippet]',
        nvim_lsp = '[LSP]',
        path = '[Path]',
        treesitter = '[Treesitter]',
      }

      return {
        snippet = {
          expand = function(args)
            luasnip.lsp_expand(args.body)
          end,
        },
        mapping = {
          ['<C-d>'] = cmp.mapping.scroll_docs(-4),
          ['<C-u>'] = cmp.mapping.scroll_docs(4),
          ['<C-Space>'] = cmp.mapping.complete(),
          ['<C-e>'] = cmp.mapping.close(),
          ['<CR>'] = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = false }),

          ['<C-n>'] = cmp.mapping.select_next_item(),
          ['<Down>'] = cmp.mapping.select_next_item(),
          ['<C-p>'] = cmp.mapping.select_prev_item(),
          ['<Up>'] = cmp.mapping.select_prev_item(),

          ['<Tab>'] = cmp.mapping(function(fallback)
            if luasnip.expand_or_locally_jumpable() then
              luasnip.expand_or_jump()
              -- elseif cmp.visible() then
              --   cmp.select_next_item()
            else
              fallback()
            end
          end, { 'i', 's' }),
          ['<S-Tab>'] = cmp.mapping(function(fallback)
            if luasnip.jumpable(-1) then
              luasnip.jump(-1)
              -- elseif cmp.visible() then
              --   cmp.select_prev_item()
            else
              fallback()
            end
          end, { 'i', 's' }),
        },
        sources = cmp.config.sources({
          { name = 'copilot', group_index = 1 },
          { name = 'nvim_lsp', group_index = 1 },
          { name = 'luasnip', group_index = 1 },
          { name = 'buffer', group_index = 2, option = { keyword_pattern = [[\k\+]] } },
          { name = 'path', group_index = 2 },
          { name = 'treesitter', group_index = 2 },
        }),
        formatting = {
          format = lspkind.cmp_format({
            menu = source_names,
            mode = 'symbol',
            symbol_map = { Copilot = '' },
          }),
        },
      }
    end,
  }
```

And this is my config for `roslyn.nvim`

```lua
{
    'seblj/roslyn.nvim',
    ft = 'cs',
    opts = function()
      local capabilities = vim.lsp.protocol.make_client_capabilities()
      capabilities = require('cmp_nvim_lsp').default_capabilities(capabilities)
      return {
        config = {
          capabilities = capabilities,
          settings = {
            ['csharp|background_analysis'] = {
              dotnet_analyzer_diagnostics_scope = 'fullSolution',
              dotnet_compiler_diagnostics_scope = 'fullSolution',
            },
            ['csharp|code_lens'] = {
              dotnet_enable_references_code_lens = true,
            },
            ['csharp|completion'] = {
              dotnet_show_name_completion_suggestions = true,
              dotnet_show_completion_items_from_unimported_namespaces = true,
              dotnet_provide_regex_completions = true,
            },
            ['csharp|inlay_hints'] = {
              csharp_enable_inlay_hints_for_implicit_object_creation = true,
              csharp_enable_inlay_hints_for_implicit_variable_types = true,
              csharp_enable_inlay_hints_for_lambda_parameter_types = true,
              csharp_enable_inlay_hints_for_types = true,
              dotnet_enable_inlay_hints_for_indexer_parameters = true,
              dotnet_enable_inlay_hints_for_literal_parameters = true,
              dotnet_enable_inlay_hints_for_object_creation_parameters = true,
              dotnet_enable_inlay_hints_for_other_parameters = true,
              dotnet_enable_inlay_hints_for_parameters = true,
              dotnet_suppress_inlay_hints_for_parameters_that_differ_only_by_suffix = true,
              dotnet_suppress_inlay_hints_for_parameters_that_match_argument_name = true,
              dotnet_suppress_inlay_hints_for_parameters_that_match_method_intent = true,
            },
          },
        },
      }
    end,
  }
```

**Comment by seblj** [comment] 2024-11-28 21:00
Does it not show any completions at all? Does it show completions for other language servers? It should just work.

You could try to remove the capabilities in the opts, because I am actually setting them automatically if you have nvim-cmp installed

**Comment by Copper0292** [comment] 2024-11-29 00:36
Yep, the capabilities were the problem. Thanks

**Comment by seblj** [comment] 2024-11-29 05:46
Good👍 I'll just reopen the issue because I want to check why this happens

**Comment by seblj** [comment] 2024-11-29 15:15
Weird, couldn't reproduce with your config. Anyways, it is fixed, so I am closing again

**Closed by seblj** 2024-11-29 15:15 UTC
