### ISSUE TITLE
Error on startup - guessed solution is a number?

### ISSUE THREAD

**Issue by brbrr** [seblj/roslyn.nvim#123] opened 2024-12-18 01:59 UTC
Hi, I'm just started using roslyn for a C# project, which has few sln solutions. 

For some reason, I started getting this error on startup:

```
Error executing vim.schedule lua callback: vim/fs.lua:0: file: expected string, got number
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/fs.lua: in function 'dirname'
        ...r/.local/share/nvim/lazy/roslyn.nvim/lua/roslyn/init.lua:49: in function <...r/.local/share/nvim/lazy/roslyn.nvim/lua/roslyn/init.lua:42>
```

**Comment by seblj** [comment] 2024-12-18 05:53
Hmm, what version of neovim do you have?

**Comment by brbrr** [comment] 2024-12-18 06:08
```
nvim -v
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1734355927
```

```
dotnet --version
9.0.101
```
I'm running macos 15.2, with roslyn installed via Mason:

```
    roslyn
      The Roslyn .NET compiler provides C# and Visual Basic languages with rich code analysis APIs

      installed version 4.13.0-3.24617.3                 
      homepage          https://github.com/dotnet/roslyn 
      languages         C#                               
      categories        LSP                              
      executables       roslyn                           
```

**Comment by seblj** [comment] 2024-12-18 09:20
Interesting, how do you configure the plugin?

**Comment by brbrr** [comment] 2024-12-18 09:24
I had some flags set (that copy-pasted from the internet), but it's reproducible with basic config:

```
  {
    'seblj/roslyn.nvim',
    ft = 'cs',
    opts = {},
  },
```

**Comment by seblj** [comment] 2024-12-18 09:29
Can you try the latest master? I don't see anything else that could potentially make this happen

**Comment by brbrr** [comment] 2024-12-18 09:36
It's much better now!

although when going to various definitions, it logs quite a few entries about loading sln's:

```
                          Roslyn project initialization complete
                          Initializing Roslyn client for projects
                          Multiple sln files found. Use `:Roslyn target` to select or change target for buffer
                          Roslyn project initialization complete
                          Roslyn project initialization complete
                          Initializing Roslyn client for projects
                          Multiple sln files found. Use `:Roslyn target` to select or change target for buffer
                          Initializing Roslyn client for /xxxxx.sln
                          Roslyn project initialization complete
                          Initializing Roslyn client for projects
                          Multiple sln files found. Use `:Roslyn target` to select or change target for buffer
```

I guess the original issue is solved. thanks, really appreciate such a fast response!

**Comment by brbrr** [comment] 2024-12-18 09:39
oh, another thing - when I selected multiple targets via `:Roslyn target` (selected via Tab), I got 4 logs: `Roslyn server stopped`

**Comment by seblj** [comment] 2024-12-18 09:59
For the first one, it might help to set `broad_search` to true

> oh, another thing - when I selected multiple targets via :Roslyn target (selected via Tab), I got 4 logs: Roslyn server stopped, not sure if that's expected

For this I am not sure what you mean? It's not supported to choose more solutions than one, and if you for example use the built in `vim.ui.select` without any plugins like telescope for example, it is impossible to choose more than one

**Comment by seblj** [comment] 2024-12-18 17:10
I am going to close this issue then since the original one is fixed. If you still have issues with it loading the wrong solution/project and such, you can open a new issue with some descriptions on what the issue is, how the solutions are laid out on the filesystem and such.

Preferably with a minimal reproduction repo that I can try with

**Closed by seblj** 2024-12-18 17:10 UTC
